import { Product, AIInsight, AlertItem, SimulationMission } from '@/types/inventory';

// Helper to generate dynamic dates relative to today
export function getRelativeDateString(offsetDays: number): string {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  return d.toISOString().split('T')[0];
}

export const INITIAL_PRODUCTS: Product[] = [
  // DAIRY (High turnover, short shelf life)
  {
    id: 'prod-1',
    name: 'Amul Taaza Homogenised Toned Milk',
    brand: 'Amul',
    sku: 'AML-MK-1000',
    barcode: '8901262010012',
    category: 'Dairy',
    unit: '1 Litre Pouch',
    quantity: 42,
    minThreshold: 15,
    batchNumber: 'BT-MLK-2409',
    manufacturingDate: getRelativeDateString(-2),
    expiryDate: getRelativeDateString(1), // Tomorrow
    shelfLifeDays: 3,
    costPrice: 52,
    sellingPrice: 56,
    discountPercent: 0,
    demandRate: 'SURGING',
    warehouseLocation: 'WATCH',
    shelfPosition: 'Cooler Shelf 1 (Back)',
    imageUrl: '🥛',
    scanned: false,
    priorityScore: 92,
    notes: 'Fast selling morning item. Move to front display.',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-2',
    name: 'Fresh Malai Paneer Block',
    brand: 'Amul',
    sku: 'AML-PNR-200',
    barcode: '8901262020202',
    category: 'Dairy',
    unit: '200g Pack',
    quantity: 18,
    minThreshold: 8,
    batchNumber: 'BT-PNR-8841',
    manufacturingDate: getRelativeDateString(-5),
    expiryDate: getRelativeDateString(2), // 2 Days left
    shelfLifeDays: 7,
    costPrice: 78,
    sellingPrice: 90,
    discountPercent: 10,
    demandRate: 'HIGH',
    warehouseLocation: 'STORAGE',
    shelfPosition: 'Back Cooler Bay B',
    imageUrl: '🧀',
    scanned: false,
    priorityScore: 88,
    notes: 'Short shelf life. Recommend 10% instant discount.',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-3',
    name: 'Mother Dairy Classic Dahi (Curd)',
    brand: 'Mother Dairy',
    sku: 'MD-CRD-400',
    barcode: '8901648011234',
    category: 'Dairy',
    unit: '400g Tub',
    quantity: 26,
    minThreshold: 10,
    batchNumber: 'BT-CRD-3301',
    manufacturingDate: getRelativeDateString(-4),
    expiryDate: getRelativeDateString(3), // 3 Days
    shelfLifeDays: 8,
    costPrice: 38,
    sellingPrice: 45,
    discountPercent: 0,
    demandRate: 'NORMAL',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Dairy Cooler 2',
    imageUrl: '🥣',
    scanned: true,
    priorityScore: 74,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-4',
    name: 'Amul Pasteurised Butter',
    brand: 'Amul',
    sku: 'AML-BTR-500',
    barcode: '8901262030508',
    category: 'Dairy',
    unit: '500g Carton',
    quantity: 14,
    minThreshold: 5,
    batchNumber: 'BT-BTR-9012',
    manufacturingDate: getRelativeDateString(-45),
    expiryDate: getRelativeDateString(14), // 14 Days
    shelfLifeDays: 180,
    costPrice: 245,
    sellingPrice: 275,
    discountPercent: 0,
    demandRate: 'HIGH',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Rack D-1',
    imageUrl: '🧈',
    scanned: true,
    priorityScore: 42,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-5',
    name: 'Epigamia Greek Yogurt (Blueberry)',
    brand: 'Epigamia',
    sku: 'EPI-YGT-120',
    barcode: '8906079010045',
    category: 'Dairy',
    unit: '120g Cup',
    quantity: 12,
    minThreshold: 6,
    batchNumber: 'BT-YGT-1142',
    manufacturingDate: getRelativeDateString(-12),
    expiryDate: getRelativeDateString(2), // 2 Days
    shelfLifeDays: 15,
    costPrice: 50,
    sellingPrice: 65,
    discountPercent: 15,
    demandRate: 'LOW',
    warehouseLocation: 'EXPIRING',
    shelfPosition: 'Front Quick Sale Rack',
    imageUrl: '🫐',
    scanned: true,
    priorityScore: 86,
    notes: 'Premium priced item, apply promotional bundle.',
    lastUpdated: new Date().toISOString(),
  },

  // BAKERY (Extremely short shelf life)
  {
    id: 'prod-6',
    name: 'Britannia 100% Whole Wheat Bread',
    brand: 'Britannia',
    sku: 'BRT-BRD-400',
    barcode: '8901063101019',
    category: 'Bakery',
    unit: '400g Loaf',
    quantity: 27,
    minThreshold: 10,
    batchNumber: 'BT-BRD-5509',
    manufacturingDate: getRelativeDateString(-2),
    expiryDate: getRelativeDateString(1), // Tomorrow
    shelfLifeDays: 4,
    costPrice: 40,
    sellingPrice: 50,
    discountPercent: 20,
    demandRate: 'SURGING',
    warehouseLocation: 'SELL_FIRST',
    shelfPosition: 'Front Entrance Display',
    imageUrl: '🍞',
    scanned: true,
    priorityScore: 94,
    notes: 'Fresh morning stock. Bundle with butter.',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-7',
    name: 'Harvest Gold White Sandwich Bread',
    brand: 'Harvest Gold',
    sku: 'HVG-BRD-700',
    barcode: '8906012340019',
    category: 'Bakery',
    unit: '700g Jumbo Loaf',
    quantity: 16,
    minThreshold: 8,
    batchNumber: 'BT-HVG-7721',
    manufacturingDate: getRelativeDateString(-1),
    expiryDate: getRelativeDateString(3), // 3 Days
    shelfLifeDays: 5,
    costPrice: 48,
    sellingPrice: 60,
    discountPercent: 0,
    demandRate: 'HIGH',
    warehouseLocation: 'WATCH',
    shelfPosition: 'Bread Rack Tier 2',
    imageUrl: '🥪',
    scanned: false,
    priorityScore: 78,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-8',
    name: 'English Oven Garlic Baguette',
    brand: 'English Oven',
    sku: 'ENG-BGT-200',
    barcode: '8906098760021',
    category: 'Bakery',
    unit: '200g Pack of 2',
    quantity: 9,
    minThreshold: 4,
    batchNumber: 'BT-ENG-9901',
    manufacturingDate: getRelativeDateString(-3),
    expiryDate: getRelativeDateString(0), // Today!
    shelfLifeDays: 4,
    costPrice: 55,
    sellingPrice: 75,
    discountPercent: 30,
    demandRate: 'LOW',
    warehouseLocation: 'EXPIRING',
    shelfPosition: 'Flash Sale Basket',
    imageUrl: '🥖',
    scanned: true,
    priorityScore: 98,
    notes: 'Expires TODAY! Must sell in next 8 hours.',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-9',
    name: 'Winkies Swiss Roll Chocolate Cake',
    brand: 'Winkies',
    sku: 'WNK-CAK-150',
    barcode: '8901230044551',
    category: 'Bakery',
    unit: '150g Box',
    quantity: 32,
    minThreshold: 10,
    batchNumber: 'BT-WNK-4412',
    manufacturingDate: getRelativeDateString(-20),
    expiryDate: getRelativeDateString(10), // 10 Days
    shelfLifeDays: 45,
    costPrice: 42,
    sellingPrice: 55,
    discountPercent: 0,
    demandRate: 'NORMAL',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Snack Shelf Tier 3',
    imageUrl: '🍰',
    scanned: true,
    priorityScore: 35,
    lastUpdated: new Date().toISOString(),
  },

  // FRUITS & VEGETABLES
  {
    id: 'prod-10',
    name: 'Shimla Royal Delicious Red Apples',
    brand: 'Farm Fresh',
    sku: 'FRM-APL-1000',
    barcode: '8908888001011',
    category: 'Fruits',
    unit: '1 Kg Crate',
    quantity: 35,
    minThreshold: 15,
    batchNumber: 'BT-APL-7740',
    manufacturingDate: getRelativeDateString(-3),
    expiryDate: getRelativeDateString(3), // 3 Days
    shelfLifeDays: 7,
    costPrice: 120,
    sellingPrice: 160,
    discountPercent: 10,
    demandRate: 'HIGH',
    warehouseLocation: 'WATCH',
    shelfPosition: 'Produce Island A',
    imageUrl: '🍎',
    scanned: true,
    priorityScore: 76,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-11',
    name: 'Robusta Golden Bananas',
    brand: 'Farm Fresh',
    sku: 'FRM-BNN-1000',
    barcode: '8908888001028',
    category: 'Fruits',
    unit: '1 Dozen Bunch',
    quantity: 22,
    minThreshold: 10,
    batchNumber: 'BT-BNN-6611',
    manufacturingDate: getRelativeDateString(-3),
    expiryDate: getRelativeDateString(1), // Tomorrow
    shelfLifeDays: 4,
    costPrice: 40,
    sellingPrice: 60,
    discountPercent: 25,
    demandRate: 'SURGING',
    warehouseLocation: 'SELL_FIRST',
    shelfPosition: 'Front Fruit Bin',
    imageUrl: '🍌',
    scanned: true,
    priorityScore: 95,
    notes: 'Skin spotted. Perfect for immediate smoothies/baking.',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-12',
    name: 'Fresh Hybrid Vine Tomatoes',
    brand: 'Farm Fresh',
    sku: 'FRM-TMT-1000',
    barcode: '8908888001035',
    category: 'Vegetables',
    unit: '1 Kg Net Bag',
    quantity: 45,
    minThreshold: 20,
    batchNumber: 'BT-TMT-3312',
    manufacturingDate: getRelativeDateString(-2),
    expiryDate: getRelativeDateString(4), // 4 Days
    shelfLifeDays: 6,
    costPrice: 28,
    sellingPrice: 40,
    discountPercent: 0,
    demandRate: 'HIGH',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Veg Tray 1',
    imageUrl: '🍅',
    scanned: true,
    priorityScore: 50,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-13',
    name: 'Pahadi White Potatoes',
    brand: 'Farm Fresh',
    sku: 'FRM-POT-5000',
    barcode: '8908888001042',
    category: 'Vegetables',
    unit: '5 Kg Sack',
    quantity: 50,
    minThreshold: 15,
    batchNumber: 'BT-POT-9922',
    manufacturingDate: getRelativeDateString(-10),
    expiryDate: getRelativeDateString(20), // 20 Days
    shelfLifeDays: 30,
    costPrice: 110,
    sellingPrice: 150,
    discountPercent: 0,
    demandRate: 'HIGH',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Ground Bin G-1',
    imageUrl: '🥔',
    scanned: true,
    priorityScore: 22,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-14',
    name: 'Organic Farm Fresh Brown Eggs',
    brand: 'Eggoz',
    sku: 'EGZ-EGG-030',
    barcode: '8906123450301',
    category: 'Dairy',
    unit: 'Tray of 30 Eggs',
    quantity: 24,
    minThreshold: 10,
    batchNumber: 'BT-EGG-4419',
    manufacturingDate: getRelativeDateString(-6),
    expiryDate: getRelativeDateString(6), // 6 Days
    shelfLifeDays: 14,
    costPrice: 180,
    sellingPrice: 225,
    discountPercent: 0,
    demandRate: 'HIGH',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Dairy Cooler 3',
    imageUrl: '🥚',
    scanned: true,
    priorityScore: 48,
    lastUpdated: new Date().toISOString(),
  },

  // BEVERAGES
  {
    id: 'prod-15',
    name: 'Real Mixed Fruit Active Juice',
    brand: 'Dabur Real',
    sku: 'DBR-REL-1000',
    barcode: '8901207010508',
    category: 'Beverages',
    unit: '1 Litre Tetra Pak',
    quantity: 38,
    minThreshold: 12,
    batchNumber: 'BT-REL-8890',
    manufacturingDate: getRelativeDateString(-60),
    expiryDate: getRelativeDateString(30), // 30 Days
    shelfLifeDays: 180,
    costPrice: 95,
    sellingPrice: 130,
    discountPercent: 5,
    demandRate: 'HIGH',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Beverage Aisle Bay 1',
    imageUrl: '🧃',
    scanned: true,
    priorityScore: 28,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-16',
    name: 'Tropicana 100% Orange Juice',
    brand: 'Tropicana',
    sku: 'TRP-ORG-1000',
    barcode: '8902080001019',
    category: 'Beverages',
    unit: '1 Litre Bottle',
    quantity: 15,
    minThreshold: 8,
    batchNumber: 'BT-TRP-2021',
    manufacturingDate: getRelativeDateString(-70),
    expiryDate: getRelativeDateString(5), // 5 Days
    shelfLifeDays: 90,
    costPrice: 105,
    sellingPrice: 145,
    discountPercent: 15,
    demandRate: 'NORMAL',
    warehouseLocation: 'WATCH',
    shelfPosition: 'Front Cooler 1',
    imageUrl: '🍊',
    scanned: true,
    priorityScore: 72,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-17',
    name: 'Paper Boat Aamras (Mango Drink)',
    brand: 'Paper Boat',
    sku: 'PB-AMR-250',
    barcode: '8906063360012',
    category: 'Beverages',
    unit: '250ml Pouch Pack of 6',
    quantity: 20,
    minThreshold: 8,
    batchNumber: 'BT-PB-4491',
    manufacturingDate: getRelativeDateString(-40),
    expiryDate: getRelativeDateString(18), // 18 Days
    shelfLifeDays: 120,
    costPrice: 160,
    sellingPrice: 210,
    discountPercent: 0,
    demandRate: 'NORMAL',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Aisle 3 Tier 2',
    imageUrl: '🥭',
    scanned: true,
    priorityScore: 30,
    lastUpdated: new Date().toISOString(),
  },

  // SNACKS & PACKAGED
  {
    id: 'prod-18',
    name: 'Parle-G Gold Glucose Biscuits',
    brand: 'Parle',
    sku: 'PRL-GLD-1000',
    barcode: '8901719101012',
    category: 'Snacks',
    unit: '1 Kg Family Pack',
    quantity: 60,
    minThreshold: 25,
    batchNumber: 'BT-PRL-1010',
    manufacturingDate: getRelativeDateString(-30),
    expiryDate: getRelativeDateString(120),
    shelfLifeDays: 180,
    costPrice: 90,
    sellingPrice: 110,
    discountPercent: 0,
    demandRate: 'SURGING',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Snack Aisle 1',
    imageUrl: '🍪',
    scanned: true,
    priorityScore: 12,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-19',
    name: 'Britannia Good Day Cashew Cookies',
    brand: 'Britannia',
    sku: 'BRT-GD-600',
    barcode: '8901063012346',
    category: 'Snacks',
    unit: '600g Multipack',
    quantity: 40,
    minThreshold: 15,
    batchNumber: 'BT-GD-3309',
    manufacturingDate: getRelativeDateString(-45),
    expiryDate: getRelativeDateString(45),
    shelfLifeDays: 180,
    costPrice: 115,
    sellingPrice: 140,
    discountPercent: 0,
    demandRate: 'HIGH',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Snack Aisle 2',
    imageUrl: '🍪',
    scanned: true,
    priorityScore: 18,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-20',
    name: "Lay's Classic Salted Potato Chips",
    brand: "Lay's",
    sku: 'LAY-SLT-115',
    barcode: '8901491101019',
    category: 'Snacks',
    unit: '115g Party Bag',
    quantity: 48,
    minThreshold: 20,
    batchNumber: 'BT-LAY-7723',
    manufacturingDate: getRelativeDateString(-50),
    expiryDate: getRelativeDateString(25),
    shelfLifeDays: 120,
    costPrice: 40,
    sellingPrice: 50,
    discountPercent: 0,
    demandRate: 'SURGING',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Hanger Display 1',
    imageUrl: '🥔',
    scanned: true,
    priorityScore: 24,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-21',
    name: 'Kurkure Masala Munch Crunchy Snack',
    brand: 'Kurkure',
    sku: 'KRK-MSL-140',
    barcode: '8901491202020',
    category: 'Snacks',
    unit: '140g Family Bag',
    quantity: 55,
    minThreshold: 20,
    batchNumber: 'BT-KRK-9901',
    manufacturingDate: getRelativeDateString(-40),
    expiryDate: getRelativeDateString(50),
    shelfLifeDays: 120,
    costPrice: 38,
    sellingPrice: 48,
    discountPercent: 0,
    demandRate: 'HIGH',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Hanger Display 2',
    imageUrl: '🌶️',
    scanned: true,
    priorityScore: 16,
    lastUpdated: new Date().toISOString(),
  },

  // STAPLES & GRAINS
  {
    id: 'prod-22',
    name: 'Aashirvaad Shudh Chakki Whole Wheat Atta',
    brand: 'Aashirvaad',
    sku: 'ASH-ATT-10K',
    barcode: '8901030010012',
    category: 'Staples',
    unit: '10 Kg Bag',
    quantity: 35,
    minThreshold: 12,
    batchNumber: 'BT-ASH-5021',
    manufacturingDate: getRelativeDateString(-25),
    expiryDate: getRelativeDateString(65),
    shelfLifeDays: 90,
    costPrice: 420,
    sellingPrice: 495,
    discountPercent: 0,
    demandRate: 'HIGH',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Grain Pallet Bay 1',
    imageUrl: '🌾',
    scanned: true,
    priorityScore: 15,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-23',
    name: 'India Gate Feast Rozzana Basmati Rice',
    brand: 'India Gate',
    sku: 'IND-RIC-5000',
    barcode: '8901725010019',
    category: 'Staples',
    unit: '5 Kg Bag',
    quantity: 28,
    minThreshold: 10,
    batchNumber: 'BT-IND-8819',
    manufacturingDate: getRelativeDateString(-60),
    expiryDate: getRelativeDateString(300),
    shelfLifeDays: 730,
    costPrice: 360,
    sellingPrice: 440,
    discountPercent: 0,
    demandRate: 'NORMAL',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Grain Pallet Bay 2',
    imageUrl: '🍚',
    scanned: true,
    priorityScore: 8,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-24',
    name: 'Tata Sampann Unpolished Toor Dal',
    brand: 'Tata Sampann',
    sku: 'TAT-TRD-1000',
    barcode: '8901031020011',
    category: 'Staples',
    unit: '1 Kg Pouch',
    quantity: 40,
    minThreshold: 15,
    batchNumber: 'BT-TAT-1190',
    manufacturingDate: getRelativeDateString(-40),
    expiryDate: getRelativeDateString(180),
    shelfLifeDays: 365,
    costPrice: 145,
    sellingPrice: 175,
    discountPercent: 0,
    demandRate: 'HIGH',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Pulses Rack A-1',
    imageUrl: '🥣',
    scanned: true,
    priorityScore: 10,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-25',
    name: 'Fortune Sunlite Refined Sunflower Oil',
    brand: 'Fortune',
    sku: 'FRT-OIL-1000',
    barcode: '8906007280014',
    category: 'Staples',
    unit: '1 Litre Pouch',
    quantity: 50,
    minThreshold: 18,
    batchNumber: 'BT-FRT-6632',
    manufacturingDate: getRelativeDateString(-45),
    expiryDate: getRelativeDateString(150),
    shelfLifeDays: 270,
    costPrice: 125,
    sellingPrice: 155,
    discountPercent: 0,
    demandRate: 'HIGH',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Oil Rack Bottom',
    imageUrl: '🌻',
    scanned: true,
    priorityScore: 12,
    lastUpdated: new Date().toISOString(),
  },

  // FROZEN
  {
    id: 'prod-26',
    name: 'McCain Crispy French Fries',
    brand: 'McCain',
    sku: 'MCN-FF-420',
    barcode: '8906004920012',
    category: 'Frozen',
    unit: '420g Bag',
    quantity: 18,
    minThreshold: 6,
    batchNumber: 'BT-MCN-3341',
    manufacturingDate: getRelativeDateString(-120),
    expiryDate: getRelativeDateString(90),
    shelfLifeDays: 365,
    costPrice: 95,
    sellingPrice: 125,
    discountPercent: 0,
    demandRate: 'NORMAL',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Deep Freezer 1',
    imageUrl: '🍟',
    scanned: true,
    priorityScore: 14,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-27',
    name: "Kwality Wall's Creamy Vanilla Tub",
    brand: "Kwality Wall's",
    sku: 'KWL-VNL-700',
    barcode: '8901030330018',
    category: 'Frozen',
    unit: '700ml Tub',
    quantity: 14,
    minThreshold: 5,
    batchNumber: 'BT-KWL-8822',
    manufacturingDate: getRelativeDateString(-60),
    expiryDate: getRelativeDateString(60),
    shelfLifeDays: 180,
    costPrice: 140,
    sellingPrice: 190,
    discountPercent: 0,
    demandRate: 'HIGH',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Ice Cream Chest 1',
    imageUrl: '🍨',
    scanned: true,
    priorityScore: 20,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-28',
    name: 'Safal Frozen Green Green Peas',
    brand: 'Safal',
    sku: 'SFL-PEA-1000',
    barcode: '8901648050011',
    category: 'Frozen',
    unit: '1 Kg Bag',
    quantity: 22,
    minThreshold: 8,
    batchNumber: 'BT-SFL-9910',
    manufacturingDate: getRelativeDateString(-90),
    expiryDate: getRelativeDateString(120),
    shelfLifeDays: 365,
    costPrice: 130,
    sellingPrice: 165,
    discountPercent: 0,
    demandRate: 'NORMAL',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Deep Freezer 2',
    imageUrl: '🫛',
    scanned: true,
    priorityScore: 15,
    lastUpdated: new Date().toISOString(),
  },

  // HOUSEHOLD
  {
    id: 'prod-29',
    name: 'Surf Excel Matic Front Load Detergent Powder',
    brand: 'Surf Excel',
    sku: 'SRF-MTC-2000',
    barcode: '8901030550012',
    category: 'Household',
    unit: '2 Kg Box',
    quantity: 25,
    minThreshold: 8,
    batchNumber: 'BT-SRF-4410',
    manufacturingDate: getRelativeDateString(-90),
    expiryDate: getRelativeDateString(600),
    shelfLifeDays: 1080,
    costPrice: 380,
    sellingPrice: 470,
    discountPercent: 0,
    demandRate: 'HIGH',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Detergent Bay 1',
    imageUrl: '🧼',
    scanned: true,
    priorityScore: 5,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: 'prod-30',
    name: 'Vim Lemon Dishwash Gel Concentrate',
    brand: 'Vim',
    sku: 'VIM-GEL-750',
    barcode: '8901030770014',
    category: 'Household',
    unit: '750ml Bottle',
    quantity: 32,
    minThreshold: 10,
    batchNumber: 'BT-VIM-1120',
    manufacturingDate: getRelativeDateString(-60),
    expiryDate: getRelativeDateString(500),
    shelfLifeDays: 730,
    costPrice: 140,
    sellingPrice: 175,
    discountPercent: 0,
    demandRate: 'HIGH',
    warehouseLocation: 'FRESH',
    shelfPosition: 'Cleaning Aisle 2',
    imageUrl: '🍋',
    scanned: true,
    priorityScore: 6,
    lastUpdated: new Date().toISOString(),
  },

  // EXPIRED SAMPLE (To test purge & alerts)
  {
    id: 'prod-31',
    name: 'Fresh Bakers Classic Croissant (Pack of 2)',
    brand: 'Fresh Bakers',
    sku: 'FBK-CRS-160',
    barcode: '8909999000018',
    category: 'Bakery',
    unit: '160g Pack',
    quantity: 4,
    minThreshold: 4,
    batchNumber: 'BT-CRS-1002',
    manufacturingDate: getRelativeDateString(-6),
    expiryDate: getRelativeDateString(-1), // Expired yesterday
    shelfLifeDays: 4,
    costPrice: 60,
    sellingPrice: 85,
    discountPercent: 50,
    demandRate: 'VERY_LOW',
    warehouseLocation: 'EXPIRED',
    shelfPosition: 'Quarantine Bin',
    imageUrl: '🥐',
    scanned: true,
    priorityScore: 100,
    notes: 'Expired stock. Must be written off and recycled.',
    lastUpdated: new Date().toISOString(),
  },
];

export const INITIAL_AI_INSIGHTS: AIInsight[] = [
  {
    id: 'ins-1',
    productId: 'prod-2',
    title: 'Move 18 Paneer Packs to Front Shelf',
    category: 'STOCK_ROTATION',
    severity: 'URGENT',
    reason: '18 packs of Amul Malai Paneer expire in 48 hours and are currently placed in Back Cooler Bay B. Historical store traffic shows 74% higher conversion on front display.',
    dataPoints: [
      { label: 'Units at Risk', value: '18 units' },
      { label: 'Current Shelf', value: 'Back Cooler B' },
      { label: 'Days Remaining', value: '2 Days' },
      { label: 'Recovery Potential', value: '₹1,260' },
    ],
    recommendedAction: 'Move 18 packs to Front Entrance Cooler and set 10% instant discount.',
    actionType: 'MOVE_FRONT',
    targetZone: 'SELL_FIRST',
    discountPercent: 10,
    potentialRecovery: 1260,
    applied: false,
    timestamp: '10 mins ago',
  },
  {
    id: 'ins-2',
    productId: 'prod-6',
    title: 'Morning Breakfast Bundle: Bread + Butter',
    category: 'MARKDOWN',
    severity: 'HIGH',
    reason: '27 Whole Wheat bread loaves expire tomorrow. Pair with Amul Butter for a 15% combo discount to accelerate morning sales velocity.',
    dataPoints: [
      { label: 'Expiring Loaves', value: '27 units' },
      { label: 'Expiry Window', value: 'Tomorrow 10 AM' },
      { label: 'Estimated Lift', value: '+65% Sell-through' },
      { label: 'Recoverable Value', value: '₹1,080' },
    ],
    recommendedAction: 'Apply 20% markdown and create "Breakfast Saver" front rack display.',
    actionType: 'APPLY_DISCOUNT',
    targetZone: 'SELL_FIRST',
    discountPercent: 20,
    potentialRecovery: 1080,
    applied: false,
    timestamp: '25 mins ago',
  },
  {
    id: 'ins-3',
    productId: 'prod-1',
    title: 'Toned Milk Surge: Morning Demand +18%',
    category: 'DEMAND_ALERT',
    severity: 'MEDIUM',
    reason: 'Milk consumption spiked 18% over the last 7 days due to local festival demand. 42 units expiring tomorrow will clear easily if moved to checkout lane.',
    dataPoints: [
      { label: 'Current Stock', value: '42 units' },
      { label: 'Demand Surge', value: '+18% Week-over-Week' },
      { label: 'Priority Placement', value: 'Checkout Lane' },
      { label: 'Protected Revenue', value: '₹2,352' },
    ],
    recommendedAction: 'Prioritize milk batch BT-MLK-2409 at checkout counter.',
    actionType: 'MOVE_FRONT',
    targetZone: 'SELL_FIRST',
    discountPercent: 0,
    potentialRecovery: 2352,
    applied: false,
    timestamp: '1 hour ago',
  },
  {
    id: 'ins-4',
    productId: 'prod-11',
    title: 'Ripe Banana Flash Clearance',
    category: 'WASTE_RISK',
    severity: 'HIGH',
    reason: '22 dozen bananas have reached peak ripeness. Mark down by 25% for smoothie shops and bakery buyers before tomorrow.',
    dataPoints: [
      { label: 'Ripening Units', value: '22 dozen' },
      { label: 'Suggested Markdown', value: '25% Off' },
      { label: 'Waste Saved', value: '₹990' },
    ],
    recommendedAction: 'Tag bananas for 25% quick clearance and move to entrance fruit stand.',
    actionType: 'APPLY_DISCOUNT',
    targetZone: 'SELL_FIRST',
    discountPercent: 25,
    potentialRecovery: 990,
    applied: false,
    timestamp: '2 hours ago',
  },
  {
    id: 'ins-5',
    productId: 'prod-31',
    title: 'Write-off Expired Croissants (4 Units)',
    category: 'WASTE_RISK',
    severity: 'URGENT',
    reason: '4 units of Fresh Bakers Croissant expired yesterday. Remove immediately from sales floor to maintain store freshness standards.',
    dataPoints: [
      { label: 'Expired Units', value: '4 packs' },
      { label: 'Write-off Loss', value: '₹240' },
      { label: 'Action', value: 'Quarantine & Composting' },
    ],
    recommendedAction: 'Move to quarantine waste bin and record manufacturer return credit.',
    actionType: 'PURGE',
    targetZone: 'EXPIRED',
    potentialRecovery: 100,
    applied: false,
    timestamp: '3 hours ago',
  },
];

export const INITIAL_ALERTS: AlertItem[] = [
  {
    id: 'alt-1',
    type: 'URGENT',
    title: '9 products expiring within 48 hours',
    description: 'Milk, Paneer, Bread and Fresh Fruits require immediate front-shelf prioritization to prevent ₹3,840 loss.',
    actionLabel: 'View Expiry Timeline',
    actionRoute: '/expiry',
    read: false,
    timestamp: '15m ago',
  },
  {
    id: 'alt-2',
    type: 'WARNING',
    title: 'Bakery stock above normal demand velocity',
    description: 'Baguettes and Artisanal Bread have slowed down. Consider bundle discounts with dairy spreads.',
    actionLabel: 'Inspect Insights',
    actionRoute: '/insights',
    read: false,
    timestamp: '1h ago',
  },
  {
    id: 'alt-3',
    type: 'INFO',
    title: 'Amul Milk demand increased by 18%',
    description: 'Festive week trend observed. Adjust daily procurement order for tomorrow morning.',
    actionLabel: 'Order Forecast',
    actionRoute: '/inventory',
    read: true,
    timestamp: '2h ago',
  },
  {
    id: 'alt-4',
    type: 'SUCCESS',
    title: '₹2,340 worth of stock successfully recovered!',
    description: 'Yesterday morning bread rotation and curd discounts cleared 100% of expiring stock without waste.',
    actionLabel: 'View Analytics',
    actionRoute: '/analytics',
    read: true,
    timestamp: '4h ago',
  },
];

export const SIMULATION_MISSIONS: SimulationMission[] = [
  {
    id: 1,
    title: 'Scan Incoming Delivery',
    objective: 'Scan all 5 delivery boxes from the arrival pallet.',
    description: 'Approach each arriving product box, press SPACE or click SCAN to read the barcode and inspect shelf life.',
    targetCount: 5,
    currentCount: 0,
    completed: false,
    rewardText: 'Unlocked: Zone Placement Guides',
  },
  {
    id: 2,
    title: 'Prioritize Urgent Stock (<3 Days)',
    objective: 'Move products expiring in under 3 days into the SELL FIRST zone.',
    description: 'Milk and Paneer are at risk! Place them in the golden SELL FIRST zone near the front counter.',
    targetCount: 3,
    currentCount: 0,
    completed: false,
    rewardText: 'Waste Prevented: +₹2,140',
  },
  {
    id: 3,
    title: 'Complete Warehouse Stock Rotation',
    objective: 'Organize healthy items into FRESH and long-dated items into STORAGE.',
    description: 'Ensure every product is in its optimal freshness zone to maximize shelf turnover.',
    targetCount: 5,
    currentCount: 0,
    completed: false,
    rewardText: 'Warehouse Fully Optimized for Today!',
  },
];
