# Build Shevolution Android APK using Windows Android SDK Build-Tools 36
$ErrorActionPreference = "Stop"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$androidDir = $scriptDir
$rootDir = (Resolve-Path "$androidDir\..").Path
$buildTools = "C:\Users\HP\AppData\Local\Android\Sdk\build-tools\36.0.0"
$platformJar = "C:\Users\HP\AppData\Local\Android\Sdk\platforms\android-36\android.jar"
$buildDir = "$androidDir\build"
$keystoreDir = "$androidDir\keystore"
$ks = "$keystoreDir\shevolution-release.p12"
$pwFile = "$keystoreDir\password.txt"

if (-not (Test-Path "$rootDir\web\out\app.html")) {
    Write-Host "Building web app first..."
    npm --prefix "$rootDir\web" run build
}

if (-not (Test-Path $buildDir)) { New-Item -ItemType Directory -Path $buildDir -Force | Out-Null }
if (-not (Test-Path $keystoreDir)) { New-Item -ItemType Directory -Path $keystoreDir -Force | Out-Null }

$password = (Get-Content $pwFile).Trim()

# 1. Clean build directory
Remove-Item "$buildDir\*" -Recurse -Force -ErrorAction SilentlyContinue
$genDir = "$buildDir\gen\com\skillizee\shevolution"
$classesDir = "$buildDir\classes"
$assetsDir = "$buildDir\assets"
New-Item -ItemType Directory -Path $genDir -Force | Out-Null
New-Item -ItemType Directory -Path $classesDir -Force | Out-Null
New-Item -ItemType Directory -Path "$assetsDir\www" -Force | Out-Null
New-Item -ItemType Directory -Path "$assetsDir\audio" -Force | Out-Null

# 2. Flavor.java (written without BOM)
$flavorContent = @"
package com.skillizee.shevolution;
/** Generated by build.ps1 */
final class Flavor {
    static final boolean DIRECT_SMS = true;
    static final String VERSION = "1.0 (sideload)";
}
"@
[System.IO.File]::WriteAllText("$genDir\Flavor.java", $flavorContent, (New-Object System.Text.UTF8Encoding($false)))

# 3. Copy assets (web/out excluding download, and audio)
Write-Host "Copying assets into APK assets directory..."
Copy-Item -Path "$rootDir\web\out\*" -Destination "$assetsDir\www" -Recurse -Force
if (Test-Path "$assetsDir\www\download") { Remove-Item "$assetsDir\www\download" -Recurse -Force }
Copy-Item -Path "$androidDir\assets\audio\*" -Destination "$assetsDir\audio" -Recurse -Force

# 4. Compile Android resources with aapt2
Write-Host "Compiling Android resources with aapt2..."
& "$buildTools\aapt2.exe" compile --dir "$androidDir\res" -o "$buildDir\res.zip"
if ($LASTEXITCODE -ne 0) { throw "aapt2 compile failed" }

# 5. Link base APK with aapt2
Write-Host "Linking APK with aapt2..."
& "$buildTools\aapt2.exe" link -o "$buildDir\base.apk" -I $platformJar `
    --manifest "$androidDir\AndroidManifest.xml" "$buildDir\res.zip" `
    -A $assetsDir --java "$buildDir\gen" `
    --min-sdk-version 24 --target-sdk-version 34 --version-code 1 --version-name "1.0"
if ($LASTEXITCODE -ne 0) { throw "aapt2 link failed" }

# Re-ensure Flavor.java is present in gen directory without BOM
[System.IO.File]::WriteAllText("$genDir\Flavor.java", $flavorContent, (New-Object System.Text.UTF8Encoding($false)))

# 6. Compile Java sources
Write-Host "Compiling Java sources..."
$javaSources = @()
$javaSources += (Get-ChildItem -Path "$buildDir\gen" -Recurse -Filter "*.java").FullName
$javaSources += (Get-ChildItem -Path "$androidDir\src\com\skillizee\shevolution" -Filter "*.java").FullName

& javac -nowarn -encoding UTF-8 --release 8 -cp $platformJar -d $classesDir $javaSources
if ($LASTEXITCODE -ne 0) { throw "javac compilation failed" }

# 7. Dex with D8
Write-Host "D8 dexing..."
$classFiles = (Get-ChildItem -Path $classesDir -Recurse -Filter "*.class").FullName
& "$buildTools\d8.bat" --min-api 24 --output $buildDir $classFiles --lib $platformJar
if ($LASTEXITCODE -ne 0) { throw "d8 dexing failed" }

# 8. Repackage into unsigned.apk with aligned/uncompressed assets
Write-Host "Repackaging unsigned APK with aligned assets..."
$pyScript = @"
import sys, zipfile, struct
src, dex, out = sys.argv[1:]
zin = zipfile.ZipFile(src)
with zipfile.ZipFile(out, 'w') as z:
    def add(name, data, stored):
        info = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
        info.compress_type = zipfile.ZIP_STORED if stored else zipfile.ZIP_DEFLATED
        if stored:
            off = z.fp.tell() + 30 + len(name.encode())
            pad = (4 - (off + 6) % 4) % 4
            info.extra = struct.pack('<HHH', 0xD935, 2 + pad, 4) + b'\0' * pad
        z.writestr(info, data)
    for i in zin.infolist():
        n = i.filename
        add(n, zin.read(i), n == 'resources.arsc' or n.endswith(('.png', '.wav', '.webp', '.woff2')))
    add('classes.dex', open(dex, 'rb').read(), False)
"@
$pyFile = "$buildDir\pack.py"
[System.IO.File]::WriteAllText($pyFile, $pyScript, (New-Object System.Text.UTF8Encoding($false)))
& python $pyFile "$buildDir\base.apk" "$buildDir\classes.dex" "$buildDir\unsigned.apk"
if ($LASTEXITCODE -ne 0) { throw "python pack failed" }

# 9. Sign APK with Sign.java
Write-Host "Signing APK with release key..."
& javac --release 11 -cp "$buildTools\lib\apksigner.jar" -d $buildDir "$androidDir\Sign.java"
if ($LASTEXITCODE -ne 0) { throw "javac Sign.java failed" }

$finalApk = "$rootDir\Shevolution.apk"
$buildApk = "$buildDir\shevolution-sideload.apk"

& java --add-exports java.base/sun.security.x509=ALL-UNNAMED --add-exports java.base/sun.security.pkcs=ALL-UNNAMED `
    -cp "$buildDir;$buildTools\lib\apksigner.jar" Sign "$buildDir\unsigned.apk" "$buildApk" "$ks" "$password"
if ($LASTEXITCODE -ne 0) { throw "Sign execution failed" }

Copy-Item $buildApk $finalApk -Force

# Also copy to web/public/download for web hosting
$dlDir = "$rootDir\web\public\download"
if (-not (Test-Path $dlDir)) { New-Item -ItemType Directory -Path $dlDir -Force | Out-Null }
Copy-Item $finalApk "$dlDir\Shevolution.apk" -Force

# Also copy into web/out/download so existing export has it immediately
$outDlDir = "$rootDir\web\out\download"
if (-not (Test-Path $outDlDir)) { New-Item -ItemType Directory -Path $outDlDir -Force | Out-Null }
Copy-Item $finalApk "$outDlDir\Shevolution.apk" -Force

Write-Host "SUCCESS! Shevolution APK generated and signed:"
Write-Host "  - Root APK: $finalApk"
Write-Host "  - Download APK: $dlDir\Shevolution.apk"
Write-Host "  - Export Download APK: $outDlDir\Shevolution.apk"
Write-Host "  - Build APK: $buildApk"
