#!/usr/bin/env bash
# Builds the Shevolution Android app (APK) without Android Studio.
#   FLAVOR=sideload (default): direct SOS texts (SEND_SMS) and SOS-text alarms (RECEIVE_SMS) — for APK installs.
#   FLAVOR=play: no SMS permissions (Google Play restricts them); SOS texts open the Messages app instead.
# Needs: web/out (run `npm --prefix web run build` first), JDK 11+, Python 3.
# Tools: aapt2 (npm "aaptjs3"), dx + apksig + Android framework (Maven Central). The release key lives in keystore/ (never committed).
set -euo pipefail
cd "$(dirname "$0")"
T=.tools; B=build; M=https://repo.maven.apache.org/maven2
FLAVOR=${FLAVOR:-sideload}; VERSION_NAME=${VERSION_NAME:-1.0}; VERSION_CODE=${VERSION_CODE:-1}
[ -f ../web/out/app.html ] || { echo "Build the web app first: npm --prefix web run build"; exit 1; }
mkdir -p $T $B keystore

[ -x $T/aapt2 ] || { (cd $T && npm pack aaptjs3@2.0.2 >/dev/null && tar xzf aaptjs3-2.0.2.tgz && cp package/bin/x64/linux/aapt2 . && chmod +x aapt2); }
[ -f $T/dx.jar ] || curl -sSfo $T/dx.jar $M/com/jakewharton/android/repackaged/dalvik-dx/16.0.1/dalvik-dx-16.0.1.jar
[ -f $T/apksig.jar ] || curl -sSfo $T/apksig.jar $M/com/android/tools/build/apksig/2.3.0/apksig-2.3.0.jar
[ -f $T/android.jar ] || curl -sSfo $T/android.jar $M/org/robolectric/android-all/14-robolectric-10818077/android-all-14-robolectric-10818077.jar

KS=keystore/shevolution-release.p12; PW_FILE=keystore/password.txt
if [ ! -f $KS ]; then
  python3 -c "import secrets;print(secrets.token_urlsafe(18))" > $PW_FILE
  keytool -genkeypair -keystore $KS -storetype PKCS12 -storepass "$(cat $PW_FILE)" -alias shevolution \
    -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Shevolution, O=Skillizee, C=IN" >/dev/null 2>&1
fi

rm -rf $B/*
mkdir -p $B/gen $B/classes $B/assets
# Manifest and build flags for the flavor
if [ "$FLAVOR" = play ]; then grep -v '<!--sms-->' AndroidManifest.xml > $B/AndroidManifest.xml; DIRECT=false; else cp AndroidManifest.xml $B/AndroidManifest.xml; DIRECT=true; fi
mkdir -p $B/gen/com/skillizee/shevolution
cat > $B/gen/com/skillizee/shevolution/Flavor.java <<J
package com.skillizee.shevolution;
/** Generated by build.sh */
final class Flavor {
    static final boolean DIRECT_SMS = $DIRECT;
    static final String VERSION = "$VERSION_NAME ($FLAVOR)";
}
J
# Assets: the UI (served offline for the real site origin) and the SOS siren
cp -r ../web/out $B/assets/www && rm -rf $B/assets/www/download
cp -r assets/audio $B/assets/audio

$T/aapt2 compile --dir res -o $B/res.zip
$T/aapt2 link -o $B/base.apk -I $T/android.jar --manifest $B/AndroidManifest.xml $B/res.zip -A $B/assets --java $B/gen \
  --min-sdk-version 24 --target-sdk-version 34 --version-code "$VERSION_CODE" --version-name "$VERSION_NAME"

javac -nowarn -encoding UTF-8 -Xlint:-options --release 8 -cp $T/android.jar -d $B/classes $(find $B/gen -name '*.java') src/com/skillizee/shevolution/*.java
java -cp $T/dx.jar com.android.dx.command.Main --dex --min-sdk-version=24 --output=$B/classes.dex $B/classes

# classes.dex in; audio, images and resources.arsc stored uncompressed and 4-byte aligned (openFd and Android 11+ need it).
python3 - "$B/base.apk" "$B/classes.dex" "$B/unsigned.apk" <<'PY'
import sys, zipfile, struct
src, dex, out = sys.argv[1:]
zin = zipfile.ZipFile(src)
with zipfile.ZipFile(out, 'w') as z:
    def add(name, data, stored):
        info = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
        info.compress_type = zipfile.ZIP_STORED if stored else zipfile.ZIP_DEFLATED
        if stored:
            off = z.fp.tell() + 30 + len(name.encode())
            pad = (4 - (off + 6) % 4) % 4
            info.extra = struct.pack('<HHH', 0xD935, 2 + pad, 4) + b'\0' * pad
        z.writestr(info, data)
    for i in zin.infolist():
        n = i.filename
        add(n, zin.read(i), n == 'resources.arsc' or n.endswith(('.png', '.wav', '.webp', '.woff2')))
    add('classes.dex', open(dex, 'rb').read(), False)
PY

javac --release 11 -cp $T/apksig.jar -d $B Sign.java
OUT=$B/shevolution-$FLAVOR.apk
java --add-exports java.base/sun.security.x509=ALL-UNNAMED --add-exports java.base/sun.security.pkcs=ALL-UNNAMED -cp "$B:$T/apksig.jar" Sign $B/unsigned.apk $OUT $KS "$(cat $PW_FILE)"

# Android App Links: lets live-location links open in the app (published by the web deploy).
FP=$(keytool -list -v -keystore $KS -storepass "$(cat $PW_FILE)" 2>/dev/null | awk '/SHA256:/{print $2; exit}')
mkdir -p ../web/public/.well-known
cat > ../web/public/.well-known/assetlinks.json <<J
[{"relation":["delegate_permission/common.handle_all_urls"],"target":{"namespace":"android_app","package_name":"com.skillizee.shevolution","sha256_cert_fingerprints":["$FP"]}}]
J
$T/aapt2 dump badging $OUT | head -2
echo "APK: android/$OUT"
