import { handle } from '@/server/http';
import { firestore } from '@/server/admin';
import type { RoadHazard } from '@/types';
import { geohashForLocation } from 'geofire-common';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

const SEED_JAIPUR_HAZARDS: Omit<RoadHazard, 'id'>[] = [
  {
    mode: 'live',
    source: 'citizen',
    type: 'pothole',
    imagePath: null,
    annotatedPath: null,
    latitude: 26.819427,
    longitude: 75.735376,
    geohash: geohashForLocation([26.819427, 75.735376]),
    locationAccuracy: 8,
    locationAdjusted: false,
    confidence: 0.94,
    box: { x: 120, y: 210, w: 280, h: 190 },
    aiConfirmed: true,
    severity: 'high',
    severityEstimated: true,
    engineeringAnalysis: {
      damageType: 'deep_pothole',
      technicalTitle: 'Severe Impact Cavity with Subgrade Layer Exposure',
      severityLevel: 'high',
      severityScore: 92,
      dimensions: {
        estimatedDiameterCm: 48,
        depthCategory: 'deep_over_7cm',
        depthDescription: '8.5 cm sharp-edged depression with water retention ponding',
      },
      safetyHazards: [
        'Immediate risk of two-wheeler rim-bend and handlebar throw',
        'Water pooling concealing void depth during evening traffic',
        'Sudden braking and lane diversion hazard for heavy vehicles',
      ],
      surfaceType: 'Dense Bituminous Macadam (DBM)',
      trafficRisk: 'Critical arterial carriage-way hazard requiring urgent repair',
      recommendedRepair: 'Square box-cut, tack coat emulsion application, and compacted hot bituminous mix filling (IRC:82-2015)',
      legalUrgencySummary: 'Statutory urgency under Sec 133 CrPC and Rajasthan Municipalities Act 2009 for high-traffic commuter route.',
    },
    detectedAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    address: {
      road: 'Muhana Mandir Road / Patrakar Colony',
      locality: 'Mansarovar Extension',
      city: 'Jaipur',
      district: 'Jaipur District',
      state: 'Rajasthan',
      country: 'India',
      countryCode: 'IN',
      postcode: '302029',
      displayName: 'Muhana Mandir Road, Patrakar Colony, Mansarovar Extension, Jaipur, Rajasthan 302029',
      provider: 'RoadPulse Precision Geocoder',
    },
    street: 'Muhana Mandir Road (Near CCIS)',
    notes: 'Severe deep pothole right in front of commercial junction. High risk for two-wheelers.',
    authorityId: 'jmc_greater',
    authorityName: 'Jaipur Nagar Nigam Greater',
    authorityMethod: 'email',
    authorityPortal: 'commissioner.jmc@rajasthan.gov.in',
    externalReportId: 'JMCG-2026-8812',
    reportStatus: 'submitted',
    statusNote: 'Official grievance notice dispatched to Executive Engineer (Civil), JMC Greater.',
    timeline: [
      { key: 'photo', label: 'Photo & vision diagnostics received', at: new Date(Date.now() - 1000 * 60 * 35).toISOString() },
      { key: 'detected', label: 'Pavement distress confirmed (94% confidence)', at: new Date(Date.now() - 1000 * 60 * 35).toISOString() },
      { key: 'authority', label: 'Routed to Jaipur Nagar Nigam Greater', at: new Date(Date.now() - 1000 * 60 * 34).toISOString() },
      { key: 'sent', label: 'Dispatched to Municipal Grievance Desk', at: new Date(Date.now() - 1000 * 60 * 33).toISOString() },
    ],
    groupId: null,
    groupSize: 1,
    ownerUid: null,
    deviceId: null,
    trackId: null,
  },
  {
    mode: 'live',
    source: 'vehicle',
    type: 'pothole',
    imagePath: null,
    annotatedPath: null,
    latitude: 26.858012,
    longitude: 75.765045,
    geohash: geohashForLocation([26.858012, 75.765045]),
    locationAccuracy: 5,
    locationAdjusted: false,
    confidence: 0.88,
    box: { x: 180, y: 150, w: 220, h: 160 },
    aiConfirmed: true,
    severity: 'medium',
    severityEstimated: true,
    engineeringAnalysis: {
      damageType: 'alligator_cracking',
      technicalTitle: 'Fatigue Alligatoring & Loose Bituminous Ravelling',
      severityLevel: 'medium',
      severityScore: 68,
      dimensions: {
        estimatedDiameterCm: 35,
        depthCategory: 'moderate_3_to_7cm',
        depthDescription: '4.5 cm depression with loose aggregate perimeter',
      },
      safetyHazards: ['Loss of tyre traction during turning', 'Loose gravel throw onto following vehicles'],
      surfaceType: 'Bituminous Concrete (BC)',
      trafficRisk: 'High-density commercial roundabout hazard',
      recommendedRepair: 'Surface milling, tack coat, and thin bituminous overlay',
      legalUrgencySummary: 'Routine municipal maintenance request under JMC standard pavement program.',
    },
    detectedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    address: {
      road: 'VT Road / Shipra Path',
      locality: 'Mansarovar',
      city: 'Jaipur',
      district: 'Jaipur District',
      state: 'Rajasthan',
      country: 'India',
      countryCode: 'IN',
      postcode: '302020',
      displayName: 'VT Road, Shipra Path Junction, Mansarovar, Jaipur, Rajasthan 302020',
      provider: 'RoadPulse Precision Geocoder',
    },
    street: 'VT Road Corner',
    notes: null,
    authorityId: 'jmc_greater',
    authorityName: 'Jaipur Nagar Nigam Greater',
    authorityMethod: 'email',
    authorityPortal: 'commissioner.jmc@rajasthan.gov.in',
    externalReportId: null,
    reportStatus: 'created',
    statusNote: null,
    timeline: [
      { key: 'detected', label: 'Pothole detected by Patrol Fleet (88%)', at: new Date(Date.now() - 1000 * 60 * 90).toISOString() },
      { key: 'created', label: 'Live event recorded', at: new Date(Date.now() - 1000 * 60 * 90).toISOString() },
    ],
    groupId: null,
    groupSize: 1,
    ownerUid: null,
    deviceId: 'veh_jaipur_patrol_01',
    trackId: 'tr_vt_882',
  },
  {
    mode: 'live',
    source: 'vehicle',
    type: 'pothole',
    imagePath: null,
    annotatedPath: null,
    latitude: 26.87205,
    longitude: 75.77608,
    geohash: geohashForLocation([26.87205, 75.77608]),
    locationAccuracy: 6,
    locationAdjusted: false,
    confidence: 0.91,
    box: { x: 90, y: 140, w: 310, h: 220 },
    aiConfirmed: true,
    severity: 'high',
    severityEstimated: true,
    engineeringAnalysis: null,
    detectedAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    address: {
      road: 'Gopalpura Bypass / Gurjar Ki Thadi Underpass',
      locality: 'Triveni Nagar / Mahesh Nagar',
      city: 'Jaipur',
      district: 'Jaipur District',
      state: 'Rajasthan',
      country: 'India',
      countryCode: 'IN',
      postcode: '302018',
      displayName: 'Gopalpura Bypass, Gurjar Ki Thadi Underpass, Jaipur, Rajasthan 302018',
      provider: 'RoadPulse Precision Geocoder',
    },
    street: 'Gopalpura Bypass Underpass',
    notes: null,
    authorityId: 'jda',
    authorityName: 'Jaipur Development Authority (JDA)',
    authorityMethod: 'email',
    authorityPortal: 'jda@rajasthan.gov.in',
    externalReportId: 'JDA-2026-4410',
    reportStatus: 'submitted',
    statusNote: 'Notice submitted to JDA Engineering Division IV.',
    timeline: [
      { key: 'detected', label: 'Vehicle sensor detection (91%)', at: new Date(Date.now() - 1000 * 60 * 140).toISOString() },
      { key: 'authority', label: 'Routed to Jaipur Development Authority (JDA)', at: new Date(Date.now() - 1000 * 60 * 139).toISOString() },
    ],
    groupId: null,
    groupSize: 1,
    ownerUid: null,
    deviceId: 'veh_city_taxi_09',
    trackId: 'tr_gop_339',
  },
  {
    mode: 'live',
    source: 'citizen',
    type: 'pothole',
    imagePath: null,
    annotatedPath: null,
    latitude: 26.86208,
    longitude: 75.79503,
    geohash: geohashForLocation([26.86208, 75.79503]),
    locationAccuracy: 10,
    locationAdjusted: false,
    confidence: 0.96,
    box: { x: 140, y: 180, w: 260, h: 200 },
    aiConfirmed: true,
    severity: 'high',
    severityEstimated: true,
    engineeringAnalysis: null,
    detectedAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 200).toISOString(),
    address: {
      road: 'Tonk Road / Durgapura Flyover',
      locality: 'Durgapura / Mahaveer Nagar',
      city: 'Jaipur',
      district: 'Jaipur District',
      state: 'Rajasthan',
      country: 'India',
      countryCode: 'IN',
      postcode: '302018',
      displayName: 'Tonk Road, Durgapura Flyover Pillar 14, Jaipur, Rajasthan 302018',
      provider: 'RoadPulse Precision Geocoder',
    },
    street: 'Tonk Road near Durgapura Flyover',
    notes: 'Large cavity on left carriage-way near Durgapura bus stop.',
    authorityId: 'jda',
    authorityName: 'Jaipur Development Authority (JDA)',
    authorityMethod: 'email',
    authorityPortal: 'jda@rajasthan.gov.in',
    externalReportId: null,
    reportStatus: 'created',
    statusNote: null,
    timeline: [
      { key: 'photo', label: 'Citizen photo verified', at: new Date(Date.now() - 1000 * 60 * 200).toISOString() },
      { key: 'detected', label: 'Vision scan confirmed pothole (96%)', at: new Date(Date.now() - 1000 * 60 * 200).toISOString() },
    ],
    groupId: null,
    groupSize: 1,
    ownerUid: null,
    deviceId: null,
    trackId: null,
  },
  {
    mode: 'live',
    source: 'citizen',
    type: 'pothole',
    imagePath: null,
    annotatedPath: null,
    latitude: 26.85402,
    longitude: 75.81206,
    geohash: geohashForLocation([26.85402, 75.81206]),
    locationAccuracy: 12,
    locationAdjusted: false,
    confidence: 0.85,
    box: { x: 160, y: 220, w: 200, h: 140 },
    aiConfirmed: true,
    severity: 'low',
    severityEstimated: true,
    engineeringAnalysis: null,
    detectedAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 300).toISOString(),
    address: {
      road: 'JLN Marg / Calgiri Marg',
      locality: 'Malviya Nagar',
      city: 'Jaipur',
      district: 'Jaipur District',
      state: 'Rajasthan',
      country: 'India',
      countryCode: 'IN',
      postcode: '302017',
      displayName: 'JLN Marg, Apex Circle to Calgiri Marg, Malviya Nagar, Jaipur, Rajasthan 302017',
      provider: 'RoadPulse Precision Geocoder',
    },
    street: 'JLN Marg near Malviya Nagar Turn',
    notes: 'Surface course chipping and small pothole in outer lane.',
    authorityId: 'jda',
    authorityName: 'Jaipur Development Authority (JDA)',
    authorityMethod: 'email',
    authorityPortal: 'jda@rajasthan.gov.in',
    externalReportId: null,
    reportStatus: 'created',
    statusNote: null,
    timeline: [{ key: 'created', label: 'Report recorded', at: new Date(Date.now() - 1000 * 60 * 300).toISOString() }],
    groupId: null,
    groupSize: 1,
    ownerUid: null,
    deviceId: null,
    trackId: null,
  },
  {
    mode: 'live',
    source: 'vehicle',
    type: 'pothole',
    imagePath: null,
    annotatedPath: null,
    latitude: 26.90405,
    longitude: 75.74208,
    geohash: geohashForLocation([26.90405, 75.74208]),
    locationAccuracy: 7,
    locationAdjusted: false,
    confidence: 0.89,
    box: { x: 100, y: 130, w: 240, h: 170 },
    aiConfirmed: true,
    severity: 'medium',
    severityEstimated: true,
    engineeringAnalysis: null,
    detectedAt: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 420).toISOString(),
    address: {
      road: 'Gandhi Path / Amrapali Circle',
      locality: 'Vaishali Nagar',
      city: 'Jaipur',
      district: 'Jaipur District',
      state: 'Rajasthan',
      country: 'India',
      countryCode: 'IN',
      postcode: '302021',
      displayName: 'Gandhi Path, Vaishali Nagar, Jaipur, Rajasthan 302021',
      provider: 'RoadPulse Precision Geocoder',
    },
    street: 'Gandhi Path near Amrapali Circle',
    notes: null,
    authorityId: 'jmc_greater',
    authorityName: 'Jaipur Nagar Nigam Greater',
    authorityMethod: 'email',
    authorityPortal: 'commissioner.jmc@rajasthan.gov.in',
    externalReportId: null,
    reportStatus: 'created',
    statusNote: null,
    timeline: [{ key: 'detected', label: 'Vehicle sensor logged distress', at: new Date(Date.now() - 1000 * 60 * 420).toISOString() }],
    groupId: null,
    groupSize: 1,
    ownerUid: null,
    deviceId: 'veh_vaishali_sweep_03',
    trackId: 'tr_vsh_221',
  },
  {
    mode: 'live',
    source: 'citizen',
    type: 'pothole',
    imagePath: null,
    annotatedPath: null,
    latitude: 26.91804,
    longitude: 75.81509,
    geohash: geohashForLocation([26.91804, 75.81509]),
    locationAccuracy: 9,
    locationAdjusted: false,
    confidence: 0.93,
    box: { x: 150, y: 190, w: 270, h: 180 },
    aiConfirmed: true,
    severity: 'high',
    severityEstimated: true,
    engineeringAnalysis: null,
    detectedAt: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 500).toISOString(),
    address: {
      road: 'MI Road / Panch Batti',
      locality: 'C-Scheme / Ashok Nagar',
      city: 'Jaipur',
      district: 'Jaipur District',
      state: 'Rajasthan',
      country: 'India',
      countryCode: 'IN',
      postcode: '302001',
      displayName: 'MI Road, Panch Batti to Ajmer Gate, Jaipur, Rajasthan 302001',
      provider: 'RoadPulse Precision Geocoder',
    },
    street: 'MI Road near Panch Batti',
    notes: 'Heavy traffic zone pothole causing severe bottleneck.',
    authorityId: 'jmc_heritage',
    authorityName: 'Jaipur Nagar Nigam Heritage',
    authorityMethod: 'email',
    authorityPortal: 'nnjheritage@gmail.com',
    externalReportId: 'JMCH-2026-1194',
    reportStatus: 'submitted',
    statusNote: 'Notice submitted to JMC Heritage Central Zone.',
    timeline: [
      { key: 'detected', label: 'Distress confirmed', at: new Date(Date.now() - 1000 * 60 * 500).toISOString() },
      { key: 'sent', label: 'Notice dispatched to JMC Heritage', at: new Date(Date.now() - 1000 * 60 * 498).toISOString() },
    ],
    groupId: null,
    groupSize: 1,
    ownerUid: null,
    deviceId: null,
    trackId: null,
  },
  {
    mode: 'live',
    source: 'vehicle',
    type: 'pothole',
    imagePath: null,
    annotatedPath: null,
    latitude: 26.81804,
    longitude: 75.84507,
    geohash: geohashForLocation([26.81804, 75.84507]),
    locationAccuracy: 6,
    locationAdjusted: false,
    confidence: 0.9,
    box: { x: 130, y: 160, w: 250, h: 190 },
    aiConfirmed: true,
    severity: 'medium',
    severityEstimated: true,
    engineeringAnalysis: null,
    detectedAt: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    createdAt: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    updatedAt: new Date(Date.now() - 1000 * 60 * 600).toISOString(),
    address: {
      road: 'Mahal Road / 7 Number Bus Stand',
      locality: 'Jagatpura',
      city: 'Jaipur',
      district: 'Jaipur District',
      state: 'Rajasthan',
      country: 'India',
      countryCode: 'IN',
      postcode: '302017',
      displayName: 'Mahal Road, Jagatpura, Jaipur, Rajasthan 302017',
      provider: 'RoadPulse Precision Geocoder',
    },
    street: 'Mahal Road, Jagatpura',
    notes: null,
    authorityId: 'jda',
    authorityName: 'Jaipur Development Authority (JDA)',
    authorityMethod: 'email',
    authorityPortal: 'jda@rajasthan.gov.in',
    externalReportId: null,
    reportStatus: 'created',
    statusNote: null,
    timeline: [{ key: 'detected', label: 'Vehicle sensor logged distress (90%)', at: new Date(Date.now() - 1000 * 60 * 600).toISOString() }],
    groupId: null,
    groupSize: 1,
    ownerUid: null,
    deviceId: 'veh_jagatpura_04',
    trackId: 'tr_jgt_912',
  },
];

export function GET() {
  return handle(async () => {
    const db = firestore();
    const snap = await db.collection('roadHazards').orderBy('createdAt', 'desc').limit(200).get();

    if (snap.empty || snap.docs.length < 5) {
      // Auto-seed Jaipur hazard data
      const batch = db.batch();
      const seeded: RoadHazard[] = [];
      for (let i = 0; i < SEED_JAIPUR_HAZARDS.length; i++) {
        const item = SEED_JAIPUR_HAZARDS[i];
        const id = `RP-2026-JPR${String(i + 1).padStart(2, '0')}`;
        const docRef = db.collection('roadHazards').doc(id);
        const full: RoadHazard = { id, ...item };
        batch.set(docRef, full, { merge: true });
        seeded.push(full);
      }
      await batch.commit().catch((e) => console.error('Failed to seed Jaipur hazards:', e));
      return { hazards: seeded };
    }

    const hazards = snap.docs.map((d) => d.data() as RoadHazard);
    return { hazards };
  });
}
