import { useEffect, useState } from 'react';
import { fmtClock } from '@engine/engine';
import { compare, main } from '@/simulation/controller';
import { useSim } from '@/simulation/useSim';
import { cloudSessions, useSessions } from '@/services/sessions';
import { useAuth } from '@/firebase/auth';
import { Btn, Card, PageHeader, Status } from '@/components/ui';
import { Timeline } from '@/components/telemetry';

export default function Events() {
  const s = useSim(main, 6);
  const l = useSim(compare.left, 4);
  const r = useSim(compare.right, 4);
  const sessions = useSessions();
  const auth = useAuth();
  const [cloud, setCloud] = useState<{ ok: boolean; items: Record<string, unknown>[]; error?: string } | null>(null);
  useEffect(() => {
    if (auth.ready) cloudSessions().then(setCloud);
  }, [auth.ready, auth.user, sessions.length]);

  const exportJson = () => {
    const blob = new Blob([JSON.stringify({ exportedAt: new Date().toISOString(), note: 'Simulated data — Smart LPG Dock prototype', live: s.events, sessions }, null, 2)], { type: 'application/json' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `lpg-dock-events-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(a.href);
  };

  return (
    <div className="space-y-4">
      <PageHeader title="Events" sub="Every entry is generated by the simulation engine at the moment it happens." right={<Btn tone="secondary" size="sm" onClick={exportJson}>Export JSON</Btn>} />
      <div className="grid gap-4 xl:grid-cols-3">
        <Card title={`Simulation · ${s.scenario === 'with' ? 'with dock' : 'without dock'}`} className="xl:col-span-1"><div className="max-h-[520px] overflow-y-auto"><Timeline s={s} startedAt={main.startedAtWall} max={100} /></div></Card>
        <Card title="Compare · without dock"><div className="max-h-[520px] overflow-y-auto"><Timeline s={l} startedAt={compare.left.startedAtWall} max={100} /></div></Card>
        <Card title="Compare · with dock"><div className="max-h-[520px] overflow-y-auto"><Timeline s={r} startedAt={compare.right.startedAtWall} max={100} /></div></Card>
      </div>
      <Card title="Saved sessions · this device" action={<Status tone="info">{sessions.length} saved</Status>}>
        {!sessions.length ? (
          <p className="text-sm text-graphite-muted">Finished runs of the main simulation are saved here automatically.</p>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full min-w-[640px] text-left text-[13px]">
              <thead className="font-mono text-[11px] uppercase text-graphite-muted"><tr><th className="py-1">Started</th><th>Scenario</th><th>Outcome</th><th>Peak gas</th><th>Duration</th><th>Cloud</th></tr></thead>
              <tbody>
                {sessions.map((x) => (
                  <tr key={x.id} className="border-t border-line">
                    <td className="py-2">{new Date(x.startedAt).toLocaleString()}</td>
                    <td>{x.scenario === 'with' ? 'With dock' : 'Without dock'} · {x.mode}</td>
                    <td><Status tone={x.outcome === 'CONTAINED' ? 'ok' : 'danger'}>{x.outcome}</Status></td>
                    <td className="font-mono">{x.peakGas.toFixed(2)} ppm</td>
                    <td className="font-mono">{fmtClock(x.durationSec)}</td>
                    <td className="text-[12px]">{x.cloud === 'saved' ? 'Saved to account' : x.cloud === 'failed' ? `Not saved: ${x.cloudError}` : 'This device only'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
      <Card title="Saved to your account (Firestore)">
        {!cloud ? <p className="text-sm text-graphite-muted">Checking…</p> : !cloud.ok ? <p className="text-sm text-graphite-muted">{cloud.error}</p> : !cloud.items.length ? <p className="text-sm text-graphite-muted">No sessions in your account yet.</p> : (
          <ul className="divide-y divide-line text-[13px]">
            {cloud.items.map((x) => (
              <li key={x.id as string} className="flex flex-wrap justify-between gap-2 py-2"><span>{new Date(x.startedAt as string).toLocaleString()} · {(x.scenario as string) === 'with' ? 'With dock' : 'Without dock'}</span><span className="font-mono font-bold">{x.outcome as string} · {x.eventCount as number} events</span></li>
            ))}
          </ul>
        )}
      </Card>
    </div>
  );
}
