package com.skillizee.lpgdock.ui;

import android.view.View;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import com.skillizee.lpgdock.services.Sessions;
import com.skillizee.lpgdock.sim.App;
import java.util.Locale;
import org.json.JSONArray;
import org.json.JSONObject;

public final class EventsScreen extends Screen {
    Parts.Timeline main, left, right;
    LinearLayout saved;
    int savedHash = 0;

    public EventsScreen(MainActivity a) {
        super(a);
    }

    @Override
    protected View build() {
        ScrollView sv = new ScrollView(a);
        LinearLayout c = Ui.col();
        c.setPadding(Ui.dp(16), Ui.dp(12), Ui.dp(16), Ui.dp(24));
        sv.addView(c);
        c.addView(Ui.text("Events", 22, Ui.INK, true));
        Ui.add(c, Ui.text("Every entry is generated by the simulation engine at the moment it happens.", 13, Ui.INK_MUTED, false), 4);
        main = new Parts.Timeline(100);
        left = new Parts.Timeline(40);
        right = new Parts.Timeline(40);
        Ui.add(c, box("Simulation", main.view), 12);
        Ui.add(c, box("Compare · without dock", left.view), 12);
        Ui.add(c, box("Compare · with dock", right.view), 12);
        saved = Ui.col();
        Ui.add(c, box("Saved sessions · this device", saved), 12);
        return sv;
    }

    LinearLayout box(String t, View v) {
        LinearLayout b = Ui.card();
        b.addView(Ui.kicker(t));
        Ui.add(b, v, 8);
        return b;
    }

    @Override
    public void update() {
        main.update(App.main);
        left.update(App.left);
        right.update(App.right);
        JSONArray l = Sessions.list(a);
        int hash = l.toString().hashCode() + 1;
        if (hash == savedHash) return;
        savedHash = hash;
        saved.removeAllViews();
        if (l.length() == 0) saved.addView(Ui.text("Finished runs of the main simulation are saved here automatically.", 13, Ui.INK_MUTED, false));
        for (int i = 0; i < l.length(); i++) {
            JSONObject o = l.optJSONObject(i);
            if (o == null) continue;
            String cloud = "saved".equals(o.optString("cloud")) ? "saved to account" : "failed".equals(o.optString("cloud")) ? "cloud save failed: " + o.optString("cloudError") : "this device only";
            Ui.add(saved, Ui.text(o.optString("startedAt").replace('T', ' ').substring(0, 19) + " · " + ("with".equals(o.optString("scenario")) ? "With dock" : "Without dock"), 13, Ui.INK, true), i == 0 ? 0 : 10);
            saved.addView(Ui.mono(String.format(Locale.US, "%s · peak %.2f ppm · %s", o.optString("outcome"), o.optDouble("peakGas"), cloud), 11.5f, "CONTAINED".equals(o.optString("outcome")) ? Ui.OK : Ui.DANGER));
        }
    }
}
