#!/usr/bin/env bash
# Builds one app's Android APK from the shared Safety Core native layer — no Android Studio or Gradle needed.
#   bash safety-core/android/build-app.sh <app-dir>          e.g. bash safety-core/android/build-app.sh sheshield
# The app provides: <app-dir>/android/app.env (identity + features), android/res (icons, sound),
# android/assets/audio/sos-alert.wav, and <app-dir>/web/out (run its web build first).
#   FLAVOR=sideload (default): SMS sent automatically (SEND_SMS) + SOS-text alarm (RECEIVE_SMS) — for APK installs.
#   FLAVOR=play: no SMS permissions (Google Play restricts them); texts open the Messages app instead.
# Tools: aapt2 (npm "aaptjs3"), dx + apksig + Android framework (Maven Central), JDK 11+, Python 3.
set -euo pipefail
CORE="$(cd "$(dirname "$0")" && pwd)"
APP="$(cd "${1:?usage: build-app.sh <app-dir>}" && pwd)"
set -a; source "$APP/android/app.env"; set +a
T="$CORE/.tools"; B="$APP/android/build"; M=https://repo.maven.apache.org/maven2
FLAVOR=${FLAVOR:-sideload}
[ -f "$APP/web/out/index.html" ] || { echo "Build the web app first: npm --prefix $APP/web run build"; exit 1; }
mkdir -p "$T" "$APP/android/keystore"

[ -x "$T/aapt2" ] || { (cd "$T" && npm pack aaptjs3@2.0.2 >/dev/null && tar xzf aaptjs3-2.0.2.tgz && cp package/bin/x64/linux/aapt2 . && chmod +x aapt2); }
[ -f "$T/dx.jar" ] || curl -sSfo "$T/dx.jar" $M/com/jakewharton/android/repackaged/dalvik-dx/16.0.1/dalvik-dx-16.0.1.jar
[ -f "$T/apksig.jar" ] || curl -sSfo "$T/apksig.jar" $M/com/android/tools/build/apksig/2.3.0/apksig-2.3.0.jar
[ -f "$T/android.jar" ] || curl -sSfo "$T/android.jar" $M/org/robolectric/android-all/14-robolectric-10818077/android-all-14-robolectric-10818077.jar

KS="$APP/android/keystore/release.p12"; PW_FILE="$APP/android/keystore/password.txt"
if [ ! -f "$KS" ]; then
  python3 -c "import secrets;print(secrets.token_urlsafe(18))" > "$PW_FILE"
  keytool -genkeypair -keystore "$KS" -storetype PKCS12 -storepass "$(cat "$PW_FILE")" -alias "$APP_ID" \
    -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=$APP_NAME, O=Skillizee, C=IN" >/dev/null 2>&1
fi

rm -rf "$B"; mkdir -p "$B/src" "$B/gen" "$B/classes" "$B/assets" "$B/res/values" "$B/res/drawable" "$B/res/mipmap-anydpi-v26"
PKG_DIR="$B/src/$(echo "$PKG" | tr . /)"; mkdir -p "$PKG_DIR"

# 1. Java: the shared safety layer, stamped with this app's package, plus generated identity/feature flags.
for f in "$CORE"/src/*.java "$APP"/android/src/*.java; do [ -f "$f" ] && sed "s/@PKG@/$PKG/g" "$f" > "$PKG_DIR/$(basename "$f")"; done
DIRECT=$([ "$FLAVOR" = play ] && echo false || echo true)
cat > "$PKG_DIR/Flavor.java" <<J
package $PKG;
/** Generated by safety-core/android/build-app.sh from android/app.env — do not edit. */
final class Flavor {
    static final String PKG = "$PKG";
    static final String APP_ID = "$APP_ID";
    static final String APP_NAME = "$APP_NAME";
    static final String HOST = "$HOST";
    static final int ACCENT = 0xFF${ACCENT#\#};
    static final int BACKGROUND = 0xFF${BACKGROUND#\#};
    static final boolean DIRECT_SMS = $DIRECT;
    static final boolean AUDIO = ${AUDIO:-false};
    static final boolean VOLUME_TRIGGER = ${VOLUME_TRIGGER:-false};
    static final String VERSION = "$VERSION_NAME ($FLAVOR)";
}
J

# 2. Manifest and resources
sed -e "s/@PKG@/$PKG/g" -e "s/@APP_NAME@/$APP_NAME/g" -e "s/@HOST@/$HOST/g" "$CORE/AndroidManifest.template.xml" > "$B/AndroidManifest.xml"
[ "$FLAVOR" = play ] && sed -i '/<!--sms-->/d' "$B/AndroidManifest.xml"
[ "${AUDIO:-false}" = true ] || sed -i '/<!--audio-->/d' "$B/AndroidManifest.xml"
cp -r "$APP/android/res/." "$B/res/"
cat > "$B/res/values/styles.xml" <<X
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="AppTheme" parent="android:Theme.Material.Light.NoActionBar">
        <item name="android:windowBackground">@drawable/splash</item>
        <item name="android:statusBarColor">$BACKGROUND</item>
        <item name="android:navigationBarColor">$BACKGROUND</item>
        <item name="android:colorAccent">$ACCENT</item>
        <item name="android:colorPrimary">$ACCENT</item>
    </style>
</resources>
X
cat > "$B/res/drawable/splash.xml" <<X
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:android="http://schemas.android.com/apk/res/android">
    <item><color android:color="$BACKGROUND" /></item>
    <item android:gravity="center" android:width="112dp" android:height="112dp" android:drawable="@drawable/splash_logo" />
</layer-list>
X
cat > "$B/res/drawable/ic_launcher_background.xml" <<X
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"><solid android:color="$ICON_BACKGROUND" /></shape>
X
cat > "$B/res/mipmap-anydpi-v26/ic_launcher.xml" <<X
<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@drawable/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
</adaptive-icon>
X

# 3. Assets: the UI (served offline for the real site origin) and the siren
cp -r "$APP/web/out" "$B/assets/www"
cp -r "$APP/android/assets/audio" "$B/assets/audio"

"$T/aapt2" compile --dir "$B/res" -o "$B/res.zip"
"$T/aapt2" link -o "$B/base.apk" -I "$T/android.jar" --manifest "$B/AndroidManifest.xml" "$B/res.zip" -A "$B/assets" --java "$B/gen" \
  --min-sdk-version 24 --target-sdk-version 34 --version-code "$VERSION_CODE" --version-name "$VERSION_NAME"
javac -nowarn -encoding UTF-8 -Xlint:-options --release 8 -cp "$T/android.jar" -d "$B/classes" $(find "$B/gen" "$B/src" -name '*.java')
java -cp "$T/dx.jar" com.android.dx.command.Main --dex --min-sdk-version=24 --output="$B/classes.dex" "$B/classes"

# 4. Package: classes.dex in; audio, images and resources.arsc stored uncompressed and 4-byte aligned.
python3 - "$B/base.apk" "$B/classes.dex" "$B/unsigned.apk" <<'PY'
import sys, zipfile, struct
src, dex, out = sys.argv[1:]
zin = zipfile.ZipFile(src)
with zipfile.ZipFile(out, 'w') as z:
    def add(name, data, stored):
        info = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
        info.compress_type = zipfile.ZIP_STORED if stored else zipfile.ZIP_DEFLATED
        if stored:
            off = z.fp.tell() + 30 + len(name.encode())
            pad = (4 - (off + 6) % 4) % 4
            info.extra = struct.pack('<HHH', 0xD935, 2 + pad, 4) + b'\0' * pad
        z.writestr(info, data)
    for i in zin.infolist():
        n = i.filename
        add(n, zin.read(i), n == 'resources.arsc' or n.endswith(('.png', '.wav', '.webp', '.woff2')))
    add('classes.dex', open(dex, 'rb').read(), False)
PY

javac --release 11 -cp "$T/apksig.jar" -d "$B" "$CORE/Sign.java"
OUT="$B/$APP_ID-$VERSION_NAME-$FLAVOR.apk"
java --add-exports java.base/sun.security.x509=ALL-UNNAMED --add-exports java.base/sun.security.pkcs=ALL-UNNAMED -cp "$B:$T/apksig.jar" Sign "$B/unsigned.apk" "$OUT" "$KS" "$(cat "$PW_FILE")"

# Android App Links: lets live-location links open in the app (published with the web deploy).
FP=$(keytool -list -v -keystore "$KS" -storepass "$(cat "$PW_FILE")" 2>/dev/null | awk '/SHA256:/{print $2; exit}')
mkdir -p "$APP/web/public/.well-known"
printf '[{"relation":["delegate_permission/common.handle_all_urls"],"target":{"namespace":"android_app","package_name":"%s","sha256_cert_fingerprints":["%s"]}}]\n' "$PKG" "$FP" > "$APP/web/public/.well-known/assetlinks.json"
"$T/aapt2" dump badging "$OUT" | head -1
echo "APK: $OUT"
